version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: react_todo
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./docker/db-store:/var/lib/postgresql/data
